# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b69408fed44c5e6c5992866be8fb177d7cd35ca43512895dcb421f99e844c3c7138382672ef811a10c7d14fd7b3ddf7f4bdd4f5881ab4938e9b1e3a51c4b93bc

test:
  secret_key_base: aeaf84fd11d0a845cfc92eeadb8f1ddf105b0a3ce796d41039dfa2494f83efb453b11a8ce8c26e36d0a391b1a2d7e06eef7ccde1a2478aaf412021c35a4b0b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
